# Generated by Django 4.2 on 2023-05-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='type_food',
            field=models.CharField(choices=[('STARTERS', 'پیش غذا'), ('MAIN DISHES', 'غذای اصلی'), ('DESERTS', 'دسسر'), ('DEINKS', 'نوشیدنی')], default='STARTERS', max_length=12, verbose_name='نوع غذا'),
        ),
    ]
