# Generated by Django 4.2 on 2023-05-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_food_type_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام و نامو خانوادگی')),
                ('email', models.EmailField(max_length=100, verbose_name='ایمیل خود را وارد کنید')),
                ('date', models.DateField(verbose_name='تاریخ را وارد کنید')),
                ('time', models.TimeField(verbose_name='ساعت را وارد کنید')),
            ],
        ),
    ]
