# Generated by Django 4.2 on 2023-05-03 12:19

from django.db import migrations, models
import foods.models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='fav',
            field=models.CharField(choices=[('هندی', 'هندی'), ('ملی', 'ملی'), ('مکزیکی', 'مکزیکی')], default=1, max_length=6, verbose_name='ترجیح غذایی'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='occasation',
            field=models.CharField(choices=[('عقد', 'عقد'), (' تولد', 'تولد'), ('سالگرد', 'سالگرد')], default=1, max_length=6, verbose_name='مناسبت'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='person',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3 ', '3'), ('4', '4')], default=1, max_length=4, verbose_name='تعداد افراد'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.CharField(default=989130000, max_length=11, validators=[foods.models.validate_phone_number], verbose_name='شماره تلفن را وارد کنید'),
        ),
    ]
