# Generated by Django 4.2 on 2023-05-04 10:34

from django.db import migrations, models
import foods.models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_reservation_fav_reservation_occasation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام و نامو خانوادگی')),
                ('email', models.EmailField(max_length=100, verbose_name='ایمیل خود را وارد کنید')),
                ('person', models.CharField(choices=[('1', '1'), ('2', '2'), ('3 ', '3'), ('4', '4')], max_length=12, verbose_name='تعداد افراد')),
                ('phone', models.CharField(max_length=11, validators=[foods.models.validate_phone_number], verbose_name='شماره تلفن را وارد کنید')),
                ('date', models.DateField(verbose_name='تاریخ را وارد کنید')),
                ('time', models.TimeField(verbose_name='ساعت را وارد کنید')),
                ('fav', models.CharField(choices=[('هندی', 'هندی'), ('ملی', 'ملی'), ('مکزیکی', 'مکزیکی')], max_length=12, verbose_name='ترجیح غذایی')),
                ('occasation', models.CharField(choices=[('عقد', 'عقد'), (' تولد', 'تولد'), ('سالگرد', 'سالگرد')], max_length=12, verbose_name='مناسبت')),
            ],
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
